version: "2"
services:
  wgtun:
    build: 
      context: .
      dockerfile: ./Dockerfile
    read_only: true
    image: 1sttun
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    ports:
      - 51820:51820
    environment:
      - WG_PORT=51820
      - NUM_CLIENTS=10
      - PRIV_NET=10.0.0.
      - EXT_IP=172.16.0.10
    network_mode: bridge #or whatever